INSERT INTO ACCOUNT (NAME, SURNAME, SEX,  EMAIL, PASSWORD, PHONE_NUMBER) VALUES ('John', 'Doe', 'MALE', 'john.doe@gmail.com', 'password', '123456789');
INSERT INTO RECIPIENT (NAME, SURNAME, SEX, EMAIL, PHONE_NUMBER) VALUES ('Olaf', 'Meier', 'FEMALE', 'olaf-meier@gmail.com', '1212212');
INSERT INTO TRANSACTIONS (RECIPIENT_ID, ACCOUNT_ID, TOPIC, RESPONSE, CUSTOM_INFO, TAGS, PRIORITY_LEVEL, STATUS, EXPIRED_AT, RESPONDED_AT, CREATED_AT)
VALUES (1, 1, 'Test Transaction', 'Response text', 'Custom info text', 'NO TAG', 'LOW', 'IN_PROGRESS', '2023-12-31', NULL, CURRENT_TIMESTAMP);
