CREATE TABLE RECIPIENT(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    SURNAME VARCHAR(255) NOT NULL,
    SEX VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(25)
);

CREATE TABLE ACCOUNT(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    SURNAME VARCHAR(255) NOT NULL,
    SEX VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(40) NOT NULL,
    PHONE_NUMBER VARCHAR(25)
);
