CREATE TABLE RECIPIENT(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    SURNAME VARCHAR(255) NOT NULL,
    SEX VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(25)
);

CREATE TABLE ACCOUNT(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    SURNAME VARCHAR(255) NOT NULL,
    SEX VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    PHONE_NUMBER VARCHAR(25)
);

CREATE TABLE TRANSACTIONS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    RECIPIENT_ID INT NOT NULL,
    ACCOUNT_ID INT NOT NULL,
    TOPIC VARCHAR(255) NOT NULL,
    RESPONSE TEXT ,
    CUSTOM_INFO TEXT,
    TAGS TEXT,
    PRIORITY_LEVEL ENUM('LOW', 'MEDIUM', 'HIGH') NOT NULL,
    STATUS ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED') NOT NULL,
    EXPIRED_AT DATE,
    RESPONDED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL,

    FOREIGN KEY(RECIPIENT_ID) REFERENCES RECIPIENT(ID) ,
    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID) ON DELETE CASCADE
);

CREATE TABLE TASK(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TRANSACTION_ID INT NOT NULL UNIQUE,

    FOREIGN KEY(TRANSACTION_ID) REFERENCES TRANSACTIONS(ID) ON DELETE CASCADE
);

CREATE TABLE TASK_FILE_UPLOAD(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TASK_ID INT NOT NULL  UNIQUE,
    FILE BLOB NOT NULL,
    FILE_TYPE ENUM('CSV', 'PDF', 'TXT') NOT NULL,
    CUSTOM_INFO TEXT,
    STATUS ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED') NOT NULL,
    STEP_NUMBER INT NOT NULL,
    UPLOADED_AT TIMESTAMP NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,

    FOREIGN KEY(TASK_ID) REFERENCES TASK(ID) ON DELETE CASCADE
);
